        const chapmanData = [
          { name: "Aberdeenshire", code: "ABD" },
          { name: "Anglesey", code: "AGY" },
          { name: "Angus (Forfarshire)", code: "ANS" },
          { name: "Antrim", code: "ANT" },
          { name: "Argyll", code: "ARL" },
          { name: "Armagh", code: "ARM" },
          { name: "Ayrshire", code: "AYR" },

          { name: "Banffshire", code: "BAN" },
          { name: "Bedfordshire", code: "BDF" },
          { name: "Berkshire", code: "BRK" },
          { name: "Berwickshire", code: "BEW" },
          { name: "Brecknockshire", code: "BRE" },
          { name: "Buckinghamshire", code: "BKM" },
          { name: "Buteshire", code: "BUT" },

          { name: "Caernarfonshire", code: "CAE" },
          { name: "Caithness", code: "CAI" },
          { name: "Cambridgeshire", code: "CAM" },
          { name: "Cardiganshire", code: "CGN" },
          { name: "Carmarthenshire", code: "CMN" },
          { name: "Cavan", code: "CAV" },
          { name: "Cheshire", code: "CHS" },
          { name: "Channel Islands", code: "CHI" },
          { name: "Clackmannanshire", code: "CLK" },
          { name: "Clare", code: "CLA" },
          { name: "Cleveland (obsolete)", code: "CLV" },
          { name: "Clwyd (obsolete)", code: "CWD" },
          { name: "Cornwall", code: "CON" },
          { name: "Cork", code: "COR" },
          { name: "Cumberland", code: "CUL" },

          { name: "Denbighshire", code: "DEN" },
          { name: "Derbyshire", code: "DBY" },
          { name: "Devon", code: "DEV" },
          { name: "Dorset", code: "DOR" },
          { name: "Down", code: "DOW" },
          { name: "Dublin", code: "DUB" },
          { name: "Dumfriesshire", code: "DFS" },
          { name: "Dunbartonshire", code: "DNB" },
          { name: "Durham", code: "DUR" },

          { name: "East Lothian", code: "ELN" },
          { name: "East Riding of Yorkshire", code: "ERY" },
          { name: "Essex", code: "ESS" },

          { name: "Fermanagh", code: "FER" },
          { name: "Fife", code: "FIF" },
          { name: "Flintshire", code: "FLN" },

          { name: "Glamorgan", code: "GLA" },
          { name: "Gloucestershire", code: "GLS" },
          { name: "Guernsey", code: "GSY" },

          { name: "Hampshire", code: "HAM" },
          { name: "Herefordshire", code: "HEF" },
          { name: "Hertfordshire", code: "HRT" },
          { name: "Huntingdonshire", code: "HUN" },

          { name: "Inverness-shire", code: "INV" },
          { name: "Isle of Man", code: "IOM" },
          { name: "Isle of Wight", code: "IOW" },
          { name: "Ireland (whole island)", code: "IRL" },

          { name: "Jersey", code: "JSY" },

          { name: "Kent", code: "KEN" },
          { name: "Kerry", code: "KER" },
          { name: "Kildare", code: "KID" },
          { name: "Kilkenny", code: "KIK" },
          { name: "Kincardineshire", code: "KCD" },
          { name: "King's County (Offaly)", code: "OFF" },
          { name: "Kinross-shire", code: "KRS" },
          { name: "Kirkcudbrightshire", code: "KKD" },

          { name: "Lanarkshire", code: "LKS" },
          { name: "Lancashire", code: "LAN" },
          { name: "Laois (Queen's County)", code: "LSL" },
          { name: "Leicestershire", code: "LEI" },
          { name: "Leitrim", code: "LET" },
          { name: "Limerick", code: "LIM" },
          { name: "Lincolnshire", code: "LIN" },
          { name: "Londonderry (Derry)", code: "LDY" },
          { name: "Longford", code: "LOG" },
          { name: "Louth", code: "LOU" },
          { name: "London", code: "LND" },

          { name: "Mayo", code: "MAY" },
          { name: "Meath", code: "MEA" },
          { name: "Merionethshire", code: "MER" },
          { name: "Middlesex", code: "MDX" },
          { name: "Midlothian", code: "MLN" },
          { name: "Monaghan", code: "MOG" },
          { name: "Monmouthshire", code: "MON" },
          { name: "Montgomeryshire", code: "MGY" },
          { name: "Moray", code: "MOR" },


          { name: "Nairnshire", code: "NAI" },
          { name: "Norfolk", code: "NFK" },
          { name: "North Riding of Yorkshire", code: "NRY" },
          { name: "Northamptonshire", code: "NTH" },
          { name: "Northumberland", code: "NBL" },
          { name: "Nottinghamshire", code: "NTT" },
          { name: "Northern Ireland", code: "NIR" },

          { name: "Orkney", code: "OKI" },
          { name: "Oxfordshire", code: "OXF" },

          { name: "Peeblesshire", code: "PEE" },
          { name: "Pembrokeshire", code: "PEM" },
          { name: "Perthshire", code: "PER" },

          { name: "Radnorshire", code: "RAD" },
          { name: "Renfrewshire", code: "RFW" },
          { name: "Roscommon", code: "ROS" },
          { name: "Ross and Cromarty", code: "ROC" },
          { name: "Roxburghshire", code: "ROX" },
          { name: "Rutland", code: "RUT" },

          { name: "Selkirkshire", code: "SEL" },
          { name: "Shetland", code: "SHI" },
          { name: "Shropshire", code: "SAL" },
          { name: "Sligo", code: "SLI" },
          { name: "Somerset", code: "SOM" },
          { name: "Staffordshire", code: "STS" },
          { name: "Stirlingshire", code: "STI" },
          { name: "Suffolk", code: "SFK" },
          { name: "Surrey", code: "SRY" },
          { name: "Sussex", code: "SSX" },
          { name: "Scotland", code: "SCT" },

          { name: "Tipperary", code: "TIP" },
          { name: "Tyrone", code: "TYR" },

          { name: "Warwickshire", code: "WAR" },
          { name: "West Lothian (Linlithgowshire)", code: "WLN" },
          { name: "West Riding of Yorkshire", code: "WRY" },
          { name: "Westmorland", code: "WES" },
          { name: "Wexford", code: "WEX" },
          { name: "Wigtownshire", code: "WIG" },
          { name: "Wiltshire", code: "WIL" },
          { name: "Worcestershire", code: "WOR" },
          { name: "Wales", code: "WLS" },

          { name: "Wirral", code: "WIR" },

          { name: "Yorkshire (historic)", code: "YKS" },
          
          
            { name: "Alabama", code: "AL" },
            { name: "Alaska", code: "AK" },
            { name: "Arizona", code: "AZ" },
            { name: "Arkansas", code: "AR" },
            { name: "California", code: "CA" },
            { name: "Colorado", code: "CO" },
            { name: "Connecticut", code: "CT" },
            { name: "Delaware", code: "DE" },
            { name: "Florida", code: "FL" },
            { name: "Georgia", code: "GA" },
            { name: "Hawaii", code: "HI" },
            { name: "Idaho", code: "ID" },
            { name: "Illinois", code: "IL" },
            { name: "Indiana", code: "IN" },
            { name: "Iowa", code: "IA" },
            { name: "Kansas", code: "KS" },
            { name: "Kentucky", code: "KY" },
            { name: "Louisiana", code: "LA" },
            { name: "Maine", code: "ME" },
            { name: "Maryland", code: "MD" },
            { name: "Massachusetts", code: "MA" },
            { name: "Michigan", code: "MI" },
            { name: "Minnesota", code: "MN" },
            { name: "Mississippi", code: "MS" },
            { name: "Missouri", code: "MO" },
            { name: "Montana", code: "MT" },
            { name: "Nebraska", code: "NE" },
            { name: "Nevada", code: "NV" },
            { name: "New Hampshire", code: "NH" },
            { name: "New Jersey", code: "NJ" },
            { name: "New Mexico", code: "NM" },
            { name: "New York", code: "NY" },
            { name: "North Carolina", code: "NC" },
            { name: "North Dakota", code: "ND" },
            { name: "Ohio", code: "OH" },
            { name: "Oklahoma", code: "OK" },
            { name: "Oregon", code: "OR" },
            { name: "Pennsylvania", code: "PA" },
            { name: "Rhode Island", code: "RI" },
            { name: "South Carolina", code: "SC" },
            { name: "South Dakota", code: "SD" },
            { name: "Tennessee", code: "TN" },
            { name: "Texas", code: "TX" },
            { name: "Utah", code: "UT" },
            { name: "Vermont", code: "VT" },
            { name: "Virginia", code: "VA" },
            { name: "Washington", code: "WA" },
            { name: "West Virginia", code: "WV" },
            { name: "Wisconsin", code: "WI" },
            { name: "Wyoming", code: "WY" },

        { name: "New South Wales", code: "NSW" },
        { name: "Victoria", code: "VIC" },
        { name: "Queensland", code: "QLD" },
        { name: "South Australia", code: "SA" },
        { name: "Western Australia", code: "WA:AU" },
        { name: "Tasmania", code: "TAS" },
        { name: "Northern Territory", code: "NT" },
        { name: "Australian Capital Territory", code: "ACT" }


        ]
